In [1]:
###
#  https://numpy.org/
###

In [2]:
import numpy as np

In [3]:
python_lista = [1,2,3,4,5]
numpy_ndarray = np.array([1,2,3,4,5])

print(f"Množenje python liste: {python_lista * 2}")
print(f"Množenje NumPy ndArray: {numpy_ndarray * 2}")


Množenje python liste: [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
Množenje NumPy ndArray: [ 2  4  6  8 10]


In [5]:
np.multiply(python_lista, 3)

array([ 3,  6,  9, 12, 15])

In [7]:
#python_lista_multiple = [1,2,3,4,5,"Alg","Pyt","Dev",3.14,False]

python_lista_multiple = [1,2,3,4,5,3.14,False]
np.multiply(python_lista_multiple, 3)

array([ 3.  ,  6.  ,  9.  , 12.  , 15.  ,  9.42,  0.  ])

In [9]:
podatci = [[1,2,3], [4,5,6], [7,8,9]]

print(podatci)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [11]:
np_podatci = np.array(podatci)
print(np_podatci)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
np_podatci.size

9

In [14]:
np_podatci.ndim

2

In [31]:
lista = [
    [[1,2,3,4],[5,6,7,8],[9,10,11,12]],
    [[13,14,15,16],[17,18,19,20],[21,22,23,24]],
    [[25,26,27,28],[29,30,31,32],[33,34,35,36]]
]
tri_d = np.array(lista)

In [32]:
tri_d.ndim

3

In [33]:
tri_d.shape

(3, 3, 4)

In [34]:
print(np_podatci.nbytes)
print(np_podatci.itemsize)
print(np_podatci.dtype)

36
4
int32


In [35]:
print(tri_d.nbytes)
print(tri_d.itemsize)
print(tri_d.dtype)

144
4
int32


In [36]:
tri_d = np.array(tri_d, dtype = np.int64)
tri_d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]],

       [[25, 26, 27, 28],
        [29, 30, 31, 32],
        [33, 34, 35, 36]]], dtype=int64)

In [37]:
print(tri_d.nbytes)
print(tri_d.itemsize)
print(tri_d.dtype)

288
8
int64


In [39]:
tri_d.shape

(3, 3, 4)

In [42]:
tri_d = tri_d.reshape(9,4)
print(tri_d.shape)
print(tri_d)

(9, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]
 [33 34 35 36]]


In [43]:
tri_d = tri_d.reshape(36)
print(tri_d.shape)
print(tri_d)

(36,)
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36]


In [44]:
tri_d.ndim

1

In [49]:
nule = np.zeros((3,5))
nule

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [51]:
jedinice = np.ones((3,2,5), dtype = np.int64)
jedinice

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]], dtype=int64)

In [53]:
pi = 3.14*jedinice
pi

array([[[3.14, 3.14, 3.14, 3.14, 3.14],
        [3.14, 3.14, 3.14, 3.14, 3.14]],

       [[3.14, 3.14, 3.14, 3.14, 3.14],
        [3.14, 3.14, 3.14, 3.14, 3.14]],

       [[3.14, 3.14, 3.14, 3.14, 3.14],
        [3.14, 3.14, 3.14, 3.14, 3.14]]])

In [55]:
array_sedmice = np.full((3,2,5),7)
array_sedmice

array([[[7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7]],

       [[7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7]],

       [[7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7]]])

In [59]:
np.arange(5,15,3)

array([ 5,  8, 11, 14])

In [60]:
np.linspace(5,15,3)

array([ 5., 10., 15.])

In [63]:
ispit = 44
dvojke = ispit/2
np.linspace(dvojke,ispit,5)

array([22. , 27.5, 33. , 38.5, 44. ])

Generirajte nekoliko novih Array objekata pomoću arange i linspace
metoda (neka ih bude minimalno 4) te im promijenite oblik po izboru. 

In [78]:
np_array = np.ones((20), dtype= np.int64)
print(np_array,"\n")

np_array= np_array.reshape(4,5)
print(np_array,"\n")

np_array[0] = np.linspace(1,5,5)
np_array[1] = np.linspace(5,1,5)
np_array[2] = np.linspace(1,10,5)
np_array[3] = np.linspace(-10,10,5)

print(np_array)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1] 

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]] 

[[  1   2   3   4   5]
 [  5   4   3   2   1]
 [  1   3   5   7  10]
 [-10  -5   0   5  10]]


In [84]:
niz_brojeva = np.random.randn(4,5)
niz_brojeva


array([[-1.15709921, -1.15349461, -0.16598391,  0.54813955,  0.11955045],
       [-0.81114563,  1.33249545,  0.93763511,  1.56556851,  0.24293581],
       [-0.35414283,  0.10852285,  0.63154604,  1.1166095 , -0.9932544 ],
       [ 0.58717849, -1.0476261 ,  1.30782532, -1.32230429, -0.62769723]])

In [97]:
niz_brojeva = np.arange(1,17).reshape(4,4)
print(niz_brojeva)
niz_brojeva.repeat(4, axis = 0)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


array([[ 1,  2,  3,  4],
       [ 1,  2,  3,  4],
       [ 1,  2,  3,  4],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 5,  6,  7,  8],
       [ 5,  6,  7,  8],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 9, 10, 11, 12],
       [ 9, 10, 11, 12],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [13, 14, 15, 16],
       [13, 14, 15, 16],
       [13, 14, 15, 16]])

In [99]:
niz_brojeva.repeat(4, axis = 1)

array([[ 1,  1,  1,  1,  2,  2,  2,  2,  3,  3,  3,  3,  4,  4,  4,  4],
       [ 5,  5,  5,  5,  6,  6,  6,  6,  7,  7,  7,  7,  8,  8,  8,  8],
       [ 9,  9,  9,  9, 10, 10, 10, 10, 11, 11, 11, 11, 12, 12, 12, 12],
       [13, 13, 13, 13, 14, 14, 14, 14, 15, 15, 15, 15, 16, 16, 16, 16]])

In [109]:
tri_d = tri_d.reshape(6,6)
tri_d = np.array(tri_d, dtype= np.int64)
tri_d

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]], dtype=int64)

In [106]:
tri_d[:2]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27]], dtype=int64)

In [112]:
tri_d[1,:4]

array([ 7,  8,  9, 10], dtype=int64)

In [113]:
tri_d[-2,-4:]

array([27, 28, 29, 30], dtype=int64)

In [114]:
tri_d[:,1]

array([ 2,  8, 14, 20, 26, 32], dtype=int64)

In [116]:
tri_d[-4:,3]

array([16, 22, 28, 34], dtype=int64)

In [117]:
tri_d[:4,-4:]

array([[ 3,  4,  5,  6],
       [ 9, 10, 11, 12],
       [15, 16, 17, 18],
       [21, 22, 23, 24]], dtype=int64)

Kreirajte niz od 64 elemenata (početni i krajnji elementi neka budu proizvoljni). Prilagodite oblik niza tako da niz bude dvodimenzionalan.

Dohvatite samo PRVI RED, samo ZADNJI RED, samo PRVI STUPAC, samo ZADNJI STUPAC. Dohvatite centralne elemente niza (najmanja tabela u sredini niza).

Pokušajte sve to napraviti s trodimenzionalnim nizom. 

In [143]:
#2d
niz_brojeva_2d = np.arange(0,64).reshape(8,8)**2
print(niz_brojeva_2d,"\n")

print("PRVI RED")
print(niz_brojeva_2d[0,:],"\n")

print("ZADNJI RED")
print(niz_brojeva_2d[-1,:],"\n")

print("PRVI STUPAC")
print(niz_brojeva_2d[:,0],"\n")

print("ZADNJI RED")
print(niz_brojeva_2d[:,-1],"\n")

print("centralne elemente")
print(niz_brojeva_2d[3:5,3:5],"\n")

[[   0    1    4    9   16   25   36   49]
 [  64   81  100  121  144  169  196  225]
 [ 256  289  324  361  400  441  484  529]
 [ 576  625  676  729  784  841  900  961]
 [1024 1089 1156 1225 1296 1369 1444 1521]
 [1600 1681 1764 1849 1936 2025 2116 2209]
 [2304 2401 2500 2601 2704 2809 2916 3025]
 [3136 3249 3364 3481 3600 3721 3844 3969]] 

PRVI RED
[ 0  1  4  9 16 25 36 49] 

ZADNJI RED
[3136 3249 3364 3481 3600 3721 3844 3969] 

PRVI STUPAC
[   0   64  256  576 1024 1600 2304 3136] 

ZADNJI RED
[  49  225  529  961 1521 2209 3025 3969] 

centralne elemente
[[ 729  784]
 [1225 1296]] 



In [132]:
#3d
niz_brojeva_3d = np.arange(0,512).reshape(8,8,8)
print(niz_brojeva_3d,"\n")

[[[  0   1   2   3   4   5   6   7]
  [  8   9  10  11  12  13  14  15]
  [ 16  17  18  19  20  21  22  23]
  [ 24  25  26  27  28  29  30  31]
  [ 32  33  34  35  36  37  38  39]
  [ 40  41  42  43  44  45  46  47]
  [ 48  49  50  51  52  53  54  55]
  [ 56  57  58  59  60  61  62  63]]

 [[ 64  65  66  67  68  69  70  71]
  [ 72  73  74  75  76  77  78  79]
  [ 80  81  82  83  84  85  86  87]
  [ 88  89  90  91  92  93  94  95]
  [ 96  97  98  99 100 101 102 103]
  [104 105 106 107 108 109 110 111]
  [112 113 114 115 116 117 118 119]
  [120 121 122 123 124 125 126 127]]

 [[128 129 130 131 132 133 134 135]
  [136 137 138 139 140 141 142 143]
  [144 145 146 147 148 149 150 151]
  [152 153 154 155 156 157 158 159]
  [160 161 162 163 164 165 166 167]
  [168 169 170 171 172 173 174 175]
  [176 177 178 179 180 181 182 183]
  [184 185 186 187 188 189 190 191]]

 [[192 193 194 195 196 197 198 199]
  [200 201 202 203 204 205 206 207]
  [208 209 210 211 212 213 214 215]
  [216 217 218 219 220

In [155]:
print("PRVI RED")
print(niz_brojeva_3d[0,:,:],"\n")

print("ZADNJI RED")
print(niz_brojeva_3d[-1,:,:],"\n")

print("PRVI STUPAC")
print(niz_brojeva_3d[:,:,0],"\n")

print("ZADNJI RED")
print(niz_brojeva_3d[:,:,-1],"\n")

print("centralne elemente")
print(niz_brojeva_3d[3,3:5,3:5],"\n")
print(niz_brojeva_3d[4,3:5,3:5],"\n")

PRVI RED
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]
 [48 49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62 63]] 

ZADNJI RED
[[448 449 450 451 452 453 454 455]
 [456 457 458 459 460 461 462 463]
 [464 465 466 467 468 469 470 471]
 [472 473 474 475 476 477 478 479]
 [480 481 482 483 484 485 486 487]
 [488 489 490 491 492 493 494 495]
 [496 497 498 499 500 501 502 503]
 [504 505 506 507 508 509 510 511]] 

PRVI STUPAC
[[  0   8  16  24  32  40  48  56]
 [ 64  72  80  88  96 104 112 120]
 [128 136 144 152 160 168 176 184]
 [192 200 208 216 224 232 240 248]
 [256 264 272 280 288 296 304 312]
 [320 328 336 344 352 360 368 376]
 [384 392 400 408 416 424 432 440]
 [448 456 464 472 480 488 496 504]] 

ZADNJI RED
[[  7  15  23  31  39  47  55  63]
 [ 71  79  87  95 103 111 119 127]
 [135 143 151 159 167 175 183 191]
 [199 207 215 223 231 239 247 255]
 [263 271 279 287 295 303 311 31

In [ ]:
#ZADACA
"""
napraviti 4x4 dvodimenzionalni niz

Sliceanjem dobiti:

    -prvi red, zadnji red,
    -prva dva, zadnja dva,
    -svaki drugi red/stupac,
    -gornja lijeva 4 elementa,
    -donja lijeva/desna
    -svaki drugi u svim smjerovima

"""